#ifndef _DB_SERVICE_CONFIG_LOG_HELPER_H_
#define _DB_SERVICE_CONFIG_LOG_HELPER_H_

#include "LogManager.h"

const int SERVICE_CONFIG_MODULE=71;
DEFINE_MODULE_XLOG(SERVICE_CONFIG_MODULE,SC_XLOG)
#define SC_SLOG(Level,Event) SLOG(SERVICE_CONFIG_MODULE,Level,Event)

#endif

