#ifndef _ASYNC_VIRTUAL_CLIENT_LOG_H_
#define _ASYNC_VIRTUAL_CLIENT_LOG_H_

#include "LogManager.h"

const int HTTP_REC_MODULE = 102;
DEFINE_MODULE_XLOG(HTTP_REC_MODULE, HTTP_REC_XLOG)
#define HTTP_REC_SLOG(Level,Event) SLOG(HTTP_REC_MODULE,Level,Event)

const int HTTP_REC_ASYNC_MODULE = 103;
DEFINE_MODULE_XLOG(HTTP_REC_ASYNC_MODULE, AHTTP_REC_XLOG)

#endif //_ASYNC_VIRTUAL_CLIENT_LOG_H_
