#ifndef _ASYNC_VIRTUAL_SERVICE_LOG_H_
#define _ASYNC_VIRTUAL_SERVICE_LOG_H_

#include "LogManager.h"

const int CVS_MODULE = 70;
DEFINE_MODULE_XLOG(CVS_MODULE,CVS_XLOG)
#define CVS_SLOG(Level,Event) SLOG(CVS_MODULE,Level,Event)

const int CVS_ASYNCLOG_MODULE = 80;
DEFINE_MODULE_XLOG(CVS_ASYNCLOG_MODULE,ACVS_XLOG)
#define ACVS_SLOG(Level,Event) SLOG(CVS_ASYNCLOG_MODULE,Level,Event)

#endif 
