#ifndef _REDIS_VIRTUAL_SERVICE_LOG_H_
#define _REDIS_VIRTUAL_SERVICE_LOG_H_

#include "LogManager.h"

const int RVS_MODULE = 75;
DEFINE_MODULE_XLOG(RVS_MODULE,RVS_XLOG)
#define RVS_SLOG(Level,Event) SLOG(RVS_MODULE,Level,Event)
	
const int RVS_ASYNCLOG_MODULE = 85;
DEFINE_MODULE_XLOG(RVS_ASYNCLOG_MODULE,ARVS_XLOG)
#define ARVS_SLOG(Level,Event) SLOG(RVS_ASYNCLOG_MODULE,Level,Event)

#endif
