#ifndef _ASYNCVIRTUALSERVICELOG_H_
#define _ASYNCVIRTUALSERVICELOG_H_

#include "LogManager.h"
const int SAP_VIRTUAL_MODULE = 71;
DEFINE_MODULE_XLOG(SAP_VIRTUAL_MODULE,SV_XLOG)

const int ASYNC_VIRTUAL_MODULE = 81;
DEFINE_MODULE_XLOG(ASYNC_VIRTUAL_MODULE,AVS_XLOG)


#define DB_XLOG SV_XLOG
#endif


