#ifndef _ASYNC_VIRTUAL_CLIENT_LOG_H_
#define _ASYNC_VIRTUAL_CLIENT_LOG_H_

#include "LogManager.h"

const int MQR_MODULE = 72;
DEFINE_MODULE_XLOG(MQR_MODULE, MQR_XLOG)

const int MQR_ASYNC_MODULE = 82;
DEFINE_MODULE_XLOG(MQR_ASYNC_MODULE, AMQR_XLOG)

#define ZK_XLOG MQR_XLOG
#define KAFKA_XLOG MQR_XLOG

#endif //_ASYNC_VIRTUAL_CLIENT_LOG_H_
