#ifndef _ASYNC_LOG_HELPER_H_
#define _ASYNC_LOG_HELPER_H_

#include "LogManager.h"
#include "SapLogHelper.h"
#include "IAsyncLogModule.h"

//detail message
const int HTTP_CONNECT_DETAIL_MODULE = 104;
const int HTTP_REQUEST_DETAIL_MODULE = 105;
const int AVENUE_REQUEST_DETAIL_MODULE = 62;

//statistic
const int HPS_STATISTICS_MODULE = 71;
const int SOS_STATISTICS_MODULE = 72;
const int MSG_STATISTICS_MODULE = 73;

const int AVENUE_REQUEST_ALL_STATISTICS_MODULE = 74;
const int SRVMSG_AVENUE_REQUEST_STATISTICS_MODULE = 75;
const int SERVICE_AVENUE_REQUEST_STATISTICS_MODULE = 76;

//self check
const int SELF_CHECK_MODULE = 81;

DEFINE_MODULE_XLOG(HTTP_CONNECT_DETAIL_MODULE, HTTP_CONNECT_XLOG)
#define HTTP_CONNECT_SLOG(Level,Event) SLOG(HTTP_CONNECT_DETAIL_MODULE,Level,Event)

DEFINE_MODULE_XLOG(HTTP_REQUEST_DETAIL_MODULE, HTTP_REQUEST_XLOG)
#define HTTP_REQUEST_SLOG(Level,Event) SLOG(HTTP_REQUEST_DETAIL_MODULE,Level,Event)

DEFINE_MODULE_XLOG(HPS_STATISTICS_MODULE, HPS_STATISTIC_XLOG)
#define HPS_STATISTIC_SLOG(Level,Event) SLOG(HPS_STATISTICS_MODULE,Level,Event)//yes

DEFINE_MODULE_XLOG(MSG_STATISTICS_MODULE, MSG_STATISTIC_XLOG)
#define MSG_STATISTIC_SLOG(Level,Event) SLOG(MSG_STATISTICS_MODULE,Level,Event)//yes


DEFINE_MODULE_XLOG(SOS_STATISTICS_MODULE, SOS_STATISTIC_XLOG)
#define SOS_STATISTIC_SLOG(Level,Event) SLOG(SOS_STATISTICS_MODULE,Level,Event)//yes

DEFINE_MODULE_XLOG(SELF_CHECK_MODULE, SELF_CEHCK_XLOG)
#define SELF_CEHCK_SLOG(Level,Event) SLOG(SELF_CHECK_MODULE,Level,Event)//yes

DEFINE_MODULE_XLOG(AVENUE_REQUEST_DETAIL_MODULE, AVENUE_REQUEST_XLOG)
#define AVENUE_REQUEST_SLOG(Level,Event) SLOG(AVENUE_REQUEST_DETAIL_MODULE,Level,Event)

DEFINE_MODULE_XLOG(AVENUE_REQUEST_ALL_STATISTICS_MODULE, ALL_AVENUE_REQUEST_STATISTIC_XLOG)
#define ALL_AVENUE_REQUEST_STATISTIC_SLOG(Level,Event) SLOG(AVENUE_REQUEST_ALL_STATISTICS_MODULE,Level,Event)//yes

DEFINE_MODULE_XLOG(SRVMSG_AVENUE_REQUEST_STATISTICS_MODULE, SRVMSG_AVENUE_REQUEST_STATISTIC_XLOG)
#define SRVMSG_AVENUE_REQUEST_STATISTIC_SLOG(Level,Event) SLOG(SRVMSG_AVENUE_REQUEST_STATISTICS_MODULE,Level,Event)//yes


DEFINE_MODULE_XLOG(SERVICE_AVENUE_REQUEST_STATISTICS_MODULE, SERVICE_AVENUE_REQUEST_STATISTIC_XLOG)
#define SERVICE_AVENUE_REQUEST_STATISTIC_SLOG(Level,Event) SLOG(SERVICE_AVENUE_REQUEST_STATISTICS_MODULE,Level,Event)//yes
#endif


